#!/bin/sh

set -e

echo "Removing unwanted packages"



### Deinstall a few unwanted packages that were pulled by tasksel
### since they have Priority: standard.
apt-get --yes purge  \
   apt-listchanges at bsd-mailx dc debian-faq doc-debian dselect \
   '^exim4*' ftp m4 mlocate mutt ncurses-term nfs-common portmap procmail python-apt \
   python-reportbug reportbug telnet texinfo time w3m wamerican

### Deinstall some other unwanted packages.
apt-get --yes purge  \
    '^aptitude*' \
    db5.1-util \
    krb5-locales \
    live-build \
    locales \
    '^openssh-blacklist*' \
    python2.6 \
    python2.6-minimal \
    rpcbind \
    tasksel \
    tasksel-data \

### Deinstall dependencies of the just removed packages.
apt-get --yes --purge autoremove
